### ISSUE TITLE
Consider sticky leading arguments

### ISSUE THREAD

**Issue by lionel-** [posit-dev/air#233]
For:

- `switch()`
- R6, S7, ggproto (e.g. https://github.com/tidyverse/ggplot2/blob/main/R/coord-map.R#L156)

I.e. functions that have one or more leading setup arguments followed by a list of key-values. A common style for these is to write the leading arguments on the same line and only expand the list of key-values.

```r
switch(foo,
  a = 1,
  b = 2
)
```

Air currently fully expands:

```r
switch(
  foo,
  a = 1,
  b = 2
)
```

We could:

- Special-case `switch()`
- Add an air.toml section with a list of functions and the number of sticky argument

Using the array-of-objects syntax for toml:

```toml
[format]

[[format.sticky]]
name = "ggproto"
n = 2

# Undo the default special-case for `switch()`
[[format.sticky]]
name = "switch"
number = 0
```
